import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { asyncHandler } from '@/lib/errorHandler';
import { createSuccessResponse, createErrorResponse } from '@/lib/apiResponse';
import { withSuperAdminAuth, AuthenticatedRequest } from '@/lib/authMiddleware';
import { requireSuperAdmin } from '@/middleware/auth';
import { z } from 'zod';
import fs from 'fs';
import path from 'path';

// Validation schemas
const backupSchema = z.object({
  includeTenants: z.boolean().default(true),
  includeUsers: z.boolean().default(true),
  includeNotifications: z.boolean().default(true),
  includeAuditLogs: z.boolean().default(false),
  includeSupportTickets: z.boolean().default(true),
  includeSystemSettings: z.boolean().default(true),
  excludeSensitiveData: z.boolean().default(true)
});

// POST /api/superadmin/backup - Generate and download database backup
export const POST = asyncHandler(async (req: NextRequest) => {
  if (process.env.NODE_ENV === 'development') {
    console.log('🔧 Generating superadmin database backup');
  }

  // Authenticate SuperAdmin
  const authResult = await requireSuperAdmin(req);
  if (authResult instanceof NextResponse) {
    return authResult;
  }

  const superAdmin = authResult as any;
  const body = await req.json();

  // Validate request body
  const validatedData = backupSchema.parse(body);
  const {
    includeTenants,
    includeUsers,
    includeNotifications,
    includeAuditLogs,
    includeSupportTickets,
    includeSystemSettings,
    excludeSensitiveData
  } = validatedData;

  try {
    // Create backup directory if it doesn't exist
    const backupDir = path.join(process.cwd(), 'backups');
    if (!fs.existsSync(backupDir)) {
      fs.mkdirSync(backupDir, { recursive: true });
    }

    // Generate backup filename
    const timestamp = new Date().toISOString().split('T')[0];
    const backupFileName = `superadmin_backup_${timestamp}.sql`;
    const backupFilePath = path.join(backupDir, backupFileName);

    // Generate SQL backup content
    let sqlContent = `-- Database Backup for SuperAdmin System\n`;
    sqlContent += `-- Generated on: ${new Date().toISOString()}\n`;
    sqlContent += `-- Generated by: ${superAdmin.email}\n`;
    sqlContent += `-- Options: ${JSON.stringify(validatedData)}\n\n`;

    // Add superadmin data
    if (includeUsers) {
      const superAdmins = await prisma.superAdmin.findMany({
        where: { isActive: true }
      });

      if (superAdmins.length > 0) {
        sqlContent += `-- SuperAdmin Data\n`;
        sqlContent += `INSERT INTO super_admins (id, email, name, password, isActive, contactNumber, createdAt, updatedAt) VALUES\n`;
        const superAdminValues = superAdmins.map(admin => {
          const password = excludeSensitiveData ? '[REDACTED]' : admin.password;
          return `('${admin.id}', '${admin.email.replace(/'/g, "''")}', '${admin.name.replace(/'/g, "''")}', `;
          return `${password.replace(/'/g, "''")}', ${admin.isActive ? 1 : 0}, `;
          return `${admin.contactNumber ? `'${admin.contactNumber.replace(/'/g, "''")}'` : 'NULL'}, `;
          return `'${admin.createdAt.toISOString()}', '${admin.updatedAt.toISOString()}')`;
        }).join(',\n');
        sqlContent += superAdminValues + ';\n\n';
      }
    }

    // Add tenants data
    if (includeTenants) {
      const tenants = await prisma.tenant.findMany({
        include: {
          users: includeUsers ? true : false,
          supportTickets: includeSupportTickets ? {
            include: {
              comments: true,
              attachments: true
            }
          } : false,
          notifications: includeNotifications ? {
            where: { targetTenantId: { not: null } }
          } : false,
          auditLogs: includeAuditLogs ? true : false
        }
      });

      if (tenants.length > 0) {
        sqlContent += `-- Tenants Data\n`;
        sqlContent += `INSERT INTO tenants (id, name, slug, domain, description, isActive, plan, region, features, createdAt, updatedAt, metadata) VALUES\n`;
        const tenantValues = tenants.map(tenant => {
          return `('${tenant.id}', '${tenant.name.replace(/'/g, "''")}', '${tenant.slug}', `;
          return `${tenant.domain ? `'${tenant.domain.replace(/'/g, "''")}'` : 'NULL'}, `;
          return `${tenant.description ? `'${tenant.description.replace(/'/g, "''")}'` : 'NULL'}, `;
          return `${tenant.isActive ? 1 : 0}, '${tenant.plan}', '${tenant.region}', `;
          return `'${tenant.features.replace(/'/g, "''")}', '${tenant.createdAt.toISOString()}', `;
          return `'${tenant.updatedAt.toISOString()}', `;
          return `${tenant.metadata ? `'${tenant.metadata.replace(/'/g, "''")}'` : 'NULL'})`;
        }).join(',\n');
        sqlContent += tenantValues + ';\n\n';

        // Add users data for tenants
        if (includeUsers) {
          const allUsers = tenants.flatMap(tenant => tenant.users || []);
          if (allUsers.length > 0) {
            sqlContent += `-- Users Data\n`;
            sqlContent += `INSERT INTO users (id, email, name, password, isActive, lastLogin, createdAt, updatedAt, tenantId, roleId, contactNumber) VALUES\n`;
            const userValues = allUsers.map(user => {
              const password = excludeSensitiveData ? '[REDACTED]' : user.password;
              return `('${user.id}', '${user.email.replace(/'/g, "''")}', '${user.name.replace(/'/g, "''")}', `;
              return `${password.replace(/'/g, "''")}', ${user.isActive ? 1 : 0}, `;
              return `${user.lastLogin ? `'${user.lastLogin.toISOString()}'` : 'NULL'}, `;
              return `'${user.createdAt.toISOString()}', '${user.updatedAt.toISOString()}', `;
              return `'${user.tenantId}', ${user.roleId ? `'${user.roleId}'` : 'NULL'}, `;
              return `${user.contactNumber ? `'${user.contactNumber.replace(/'/g, "''")}'` : 'NULL'})`;
            }).join(',\n');
            sqlContent += userValues + ';\n\n';
          }
        }

        // Add support tickets data
        if (includeSupportTickets) {
          const allTickets = tenants.flatMap(tenant => tenant.supportTickets || []);
          if (allTickets.length > 0) {
            sqlContent += `-- Support Tickets Data\n`;
            sqlContent += `INSERT INTO support_tickets (id, title, description, category, status, priority, isForwarded, createdAt, updatedAt, tenantId, userId) VALUES\n`;
            const ticketValues = allTickets.map(ticket => {
              return `('${ticket.id}', '${ticket.title.replace(/'/g, "''")}', '${ticket.description.replace(/'/g, "''")}', `;
              return `'${ticket.category}', '${ticket.status}', '${ticket.priority}', ${ticket.isForwarded ? 1 : 0}, `;
              return `'${ticket.createdAt.toISOString()}', '${ticket.updatedAt.toISOString()}', `;
              return `'${ticket.tenantId}', ${ticket.userId ? `'${ticket.userId}'` : 'NULL'})`;
            }).join(',\n');
            sqlContent += ticketValues + ';\n\n';

            // Add ticket comments
            const allComments = allTickets.flatMap(ticket => ticket.comments || []);
            if (allComments.length > 0) {
              sqlContent += `-- Support Ticket Comments Data\n`;
              sqlContent += `INSERT INTO support_ticket_comments (id, text, createdAt, updatedAt, ticketId, commentedBy, commenterType) VALUES\n`;
              const commentValues = allComments.map(comment => {
                return `('${comment.id}', '${comment.text.replace(/'/g, "''")}', `;
                return `'${comment.createdAt.toISOString()}', '${comment.updatedAt.toISOString()}', `;
                return `'${comment.ticketId}', '${comment.commentedBy}', '${comment.commenterType}')`;
              }).join(',\n');
              sqlContent += commentValues + ';\n\n';
            }

            // Add ticket attachments
            const allAttachments = allTickets.flatMap(ticket => ticket.attachments || []);
            if (allAttachments.length > 0) {
              sqlContent += `-- Support Ticket Attachments Data\n`;
              sqlContent += `INSERT INTO support_ticket_attachments (id, filename, originalName, mimeType, size, path, createdAt, ticketId) VALUES\n`;
              const attachmentValues = allAttachments.map(attachment => {
                return `('${attachment.id}', '${attachment.filename.replace(/'/g, "''")}', `;
                return `'${attachment.originalName.replace(/'/g, "''")}', '${attachment.mimeType}', `;
                return `${attachment.size}, '${attachment.path.replace(/'/g, "''")}', `;
                return `'${attachment.createdAt.toISOString()}', '${attachment.ticketId}')`;
              }).join(',\n');
              sqlContent += attachmentValues + ';\n\n';
            }
          }
        }

        // Add notifications data
        if (includeNotifications) {
          const allNotifications = tenants.flatMap(tenant => tenant.notifications || []);
          if (allNotifications.length > 0) {
            sqlContent += `-- Notifications Data\n`;
            sqlContent += `INSERT INTO notifications (id, title, message, isRead, isActive, createdAt, updatedAt, createdBy, priority, targetTenantId, targetType) VALUES\n`;
            const notificationValues = allNotifications.map(notification => {
              return `('${notification.id}', '${notification.title.replace(/'/g, "''")}', `;
              return `'${notification.message.replace(/'/g, "''")}', ${notification.isRead ? 1 : 0}, `;
              return `${notification.isActive ? 1 : 0}, '${notification.createdAt.toISOString()}', `;
              return `'${notification.updatedAt.toISOString()}', ${notification.createdBy ? `'${notification.createdBy}'` : 'NULL'}, `;
              return `'${notification.priority}', '${notification.targetTenantId}', '${notification.targetType}')`;
            }).join(',\n');
            sqlContent += notificationValues + ';\n\n';
          }
        }

        // Add audit logs data
        if (includeAuditLogs) {
          const allAuditLogs = tenants.flatMap(tenant => tenant.auditLogs || []);
          if (allAuditLogs.length > 0) {
            sqlContent += `-- Audit Logs Data\n`;
            sqlContent += `INSERT INTO audit_logs (id, action, details, ipAddress, userAgent, createdAt, tenantId, userId, superAdminId) VALUES\n`;
            const auditValues = allAuditLogs.map(log => {
              return `('${log.id}', '${log.action.replace(/'/g, "''")}', `;
              return `${log.details ? `'${log.details.replace(/'/g, "''")}'` : 'NULL'}, `;
              return `${log.ipAddress ? `'${log.ipAddress.replace(/'/g, "''")}'` : 'NULL'}, `;
              return `${log.userAgent ? `'${log.userAgent.replace(/'/g, "''")}'` : 'NULL'}, `;
              return `'${log.createdAt.toISOString()}', '${log.tenantId}', `;
              return `${log.userId ? `'${log.userId}'` : 'NULL'}, ${log.superAdminId ? `'${log.superAdminId}'` : 'NULL'})`;
            }).join(',\n');
            sqlContent += auditValues + ';\n\n';
          }
        }
      }
    }

    // Add system settings data
    if (includeSystemSettings) {
      const systemSettings = await prisma.systemSetting.findMany();
      if (systemSettings.length > 0) {
        sqlContent += `-- System Settings Data\n`;
        sqlContent += `INSERT INTO system_settings (id, key, value, description, createdAt, updatedAt) VALUES\n`;
        const settingValues = systemSettings.map(setting => {
          return `('${setting.id}', '${setting.key.replace(/'/g, "''")}', `;
          return `'${setting.value.replace(/'/g, "''")}', `;
          return `${setting.description ? `'${setting.description.replace(/'/g, "''")}'` : 'NULL'}, `;
          return `'${setting.createdAt.toISOString()}', '${setting.updatedAt.toISOString()}')`;
        }).join(',\n');
        sqlContent += settingValues + ';\n\n';
      }
    }

    // Write backup file
    fs.writeFileSync(backupFilePath, sqlContent);

    // Log the action in audit logs
    await prisma.auditLog.create({
      data: {
        action: 'create_backup',
        details: `Superadmin backup generated: ${backupFileName} with options: ${JSON.stringify(validatedData)}`,
        ipAddress: req.headers.get('x-forwarded-for') || req.headers.get('x-real-ip') || 'unknown',
        userAgent: req.headers.get('user-agent') || 'unknown',
        superAdminId: superAdmin.id,
        createdAt: new Date()
      }
    });

    if (process.env.NODE_ENV === 'development') {
      console.log('✅ Superadmin backup generated successfully');
    }

    // Return the backup file
    const fileBuffer = fs.readFileSync(backupFilePath);
    
    // Clean up the file after reading
    fs.unlinkSync(backupFilePath);

    const headers = new Headers();
    headers.set('Content-Type', 'application/sql');
    headers.set('Content-Disposition', `attachment; filename="${backupFileName}"`);

    return new NextResponse(fileBuffer, {
      status: 200,
      headers
    });

  } catch (error) {
    if (process.env.NODE_ENV === 'development') {
      console.error('❌ Error generating superadmin backup:', error);
    }
    throw error;
  }
}); 