-- AlterTable
ALTER TABLE `role_permissions` ADD COLUMN `canCreate` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `canDelete` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `canRead` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `canUpdate` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `canViewAll` BOOLEAN NOT NULL DEFAULT false;
